version: "3.8"

services:
<<<<<<< HEAD
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php-app
    ports:
      - "8080:80" # Map port 8080 on the host to port 80 in the container
    volumes:
      - .:/var/www/html # Mount the current directory to the container
    depends_on:
      - db # Ensure the database starts before the app
    environment:
      - DB_HOST=db
      - DB_USER=admin
      - DB_PASS=admin
      - DB_NAME=restaurantdb

  db:
    image: mysql:5.7
    container_name: mysql-db
=======
  php-apache:
    build: .
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - mysql
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=admin
      - MYSQL_DATABASE=restaurantdb

  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
>>>>>>> 60b29bb18524458d89b5510aff8f2849b29f7674
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: restaurantdb
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    ports:
<<<<<<< HEAD
      - "3306:3306" # Map port 3306 on the host to port 3306 in the container
    volumes:
      - db_data:/var/lib/mysql # Persistent storage for the database

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    depends_on:
      - db # Ensure MySQL is running before starting phpMyAdmin
    environment:
      PMA_HOST: db # Connect phpMyAdmin to the 'db' service
      PMA_USER: admin
      PMA_PASSWORD: admin
    ports:
      - "8081:80" # Map port 8081 on the host to port 80 in the container
    volumes:
      - /sessions # phpMyAdmin session management (optional)

volumes:
  db_data: # Named volume for database persistence
=======
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  db_data:
>>>>>>> 60b29bb18524458d89b5510aff8f2849b29f7674
